"""Shared synthetic ground truth.

Every fixture here builds data from *known* pRF parameters, so any test can compare what the
fitter reports against what actually generated the signal.
"""

from __future__ import annotations

import numpy as np
import pytest

from cortexprobe.config import FitConfig, StimulusConfig
from cortexprobe.geometry import Grid
from cortexprobe.prf.fit import PRFFitter
from cortexprobe.prf.model import GaussianReceptiveField, predict
from cortexprobe.stimuli import ApertureSequence, build_apertures

RESOLUTION = 64


@pytest.fixture(scope="session")
def grid() -> Grid:
    return Grid(RESOLUTION)


@pytest.fixture(scope="session")
def stimulus_config() -> StimulusConfig:
    return StimulusConfig(resolution=RESOLUTION, n_steps=20, directions=(0, 45, 90, 135))


@pytest.fixture(scope="session")
def sequence(stimulus_config: StimulusConfig) -> ApertureSequence:
    return build_apertures(stimulus_config, "bar")


@pytest.fixture(scope="session")
def apertures(sequence: ApertureSequence) -> np.ndarray:
    return sequence.as_float()


@pytest.fixture(scope="session")
def fit_config() -> FitConfig:
    return FitConfig(grid_size=10, sigma_bounds=(1.0, 10.0))


@pytest.fixture(scope="session")
def fitter(grid: Grid, apertures: np.ndarray, fit_config: FitConfig) -> PRFFitter:
    return PRFFitter(grid, apertures, fit_config)


def synthesise(
    grid: Grid,
    apertures: np.ndarray,
    truth: tuple,
    beta: float = 3.0,
    baseline: float = 0.5,
    noise: float = 0.0,
    seed: int = 0,
) -> np.ndarray:
    """Activation timecourse generated by a known pRF, optionally with Gaussian noise.

    Noise is scaled relative to the clean signal's own standard deviation, so ``noise=0.2``
    means the same signal-to-noise ratio regardless of pRF size or position.
    """
    x0, y0, sigma = truth
    weights = GaussianReceptiveField(x0, y0, sigma).weights(grid)
    clean = beta * predict(weights, apertures) + baseline
    if noise <= 0.0:
        return clean
    rng = np.random.default_rng(seed)
    return clean + rng.normal(0.0, noise * float(np.std(clean)), size=clean.shape)


def autocorrelated_noise(n_frames: int, width: int = 3, seed: int = 21) -> np.ndarray:
    """Noise with frame-to-frame correlation but no pRF structure.

    Real activation timecourses are smooth in time: a bar moving one step changes the input
    only slightly, so consecutive frames are correlated. White noise is not a realistic
    stand-in when the question is whether a validation split leaks.
    """
    rng = np.random.default_rng(seed)
    kernel = np.ones(width) / width
    return np.convolve(rng.normal(size=n_frames), kernel, mode="same")


@pytest.fixture(scope="session")
def default_stimulus_config() -> StimulusConfig:
    """The configuration a user gets with no overrides at all.

    Every other fixture here pins a smaller stimulus so the suite stays fast, with directions
    (0, 45, 90, 135). Those particular angles contain no pair 180 degrees apart, so that config
    cannot exhibit the duplicate-sweep leak the shipped default once had. That is a property of
    the angles chosen, not of choosing four of them -- (0, 90, 180, 270) has two such pairs and
    is equally legal -- which is exactly why the default is fixtured here and asserted against
    directly rather than trusted to be representative.
    """
    return StimulusConfig()
